version: '2'
services:
  jenkins:
    build: .
    image: deelthor/jenkins-build-pipeline
    network_mode: "bridge"
    ports:
      - "8080:8080"
    volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
       - "/usr/local/bin/docker:/usr/bin/docker"
